### ISSUE TITLE
Display both author & sponsor at top & bottom of post

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-sponsors#176]
One Newspack publisher (CT News Junkie) finds:

> … [stories] get less engagement if there's no face that goes with the op-ed. The author is important, but in the current setup, the name of the sponsor replaces the byline, and then the sponsor appears again at the bottom. In my opinion, this is overkill. The author's byline ought to be up there, and perhaps it should work like a dual byline. Selecting both an author user and a sponsor could lead to the author's name first, and then over to the right the sponsor:
>
> By Ken Gagne / Sponsored by Newspack

Similarly:

> current sponsorship settings also preclude the appearance of the author's bio at the bottom. Displaying them both is the way to go.

Ideally, these would be options that can be set on a per-post basis, so that publishers who are already running this plugin won't find the default layout suddenly changed on them.

**Comment by tmmbecker** [comment]
CT News Junkie asked about this but others have mentioned it as well.

**Comment by allykmyta** [comment]
LProfile has also requested this.
