### ISSUE TITLE
Version mismatch in release vs source code

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-sponsors#203]
v1.10.0 is released, however source code and WP admin still shows v1.8.0

https://github.com/Automattic/newspack-sponsors/blob/cf687ec13f6e8946fc60628c8ba0c9f9bfaf96e5/newspack-sponsors.php#L10

**Comment by gamebits** [comment]
Thanks! This was resolved in v1.10.1. Closing.
