### ISSUE TITLE
Possible missing option to only display post author, or incorrect label?

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-sponsors#206]
In #186, an option was added to switch what's shown for the author on sponsored posts. 

The dropdown only lets you select between showing the sponsor or the author and the sponsor, but the label for the dropdown says the options are to "Show the sponsor, the author byline, or both."

![image](https://user-images.githubusercontent.com/177561/191826320-05e214ea-b4a5-44f9-adf9-b958d4ee5853.png)

![image](https://user-images.githubusercontent.com/177561/191825691-97ef7564-064c-4ff9-a806-529da9beaf55.png)

I believe the label is correct, and not the options, but I'm not 100% sure -- @dkoo can you confirm either way?

**Comment by dkoo** [comment]
My thinking was that if you didn't want to show the sponsor at all, the sponsor should be an underwriter. Is there a use case for a "direct" sponsor without the underwriter treatment?

**Comment by laurelfulford** [comment]
Yeah that's a good point re: using an underwriter instead of a native sponsor 🤔 I don't think there's a case for yet another presentation of the sponsors yet -- it feels a little like it could border on not noticeable enough. The author + sponsor combo makes the sponsor look more subtle on single posts, though I'm half wondering if the issue with showing both is on the homepage, since it can feel a little crowded. 

I'm going to leave this open to fix the label, and can follow up on the original support request this came from. Thanks @dkoo!
