### ISSUE TITLE
Move the sponsored logo above Jetpack's related posts

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-sponsors#61]
The Sponsor information and logo currently displays at the very bottom of the story, which puts it below Jetpack's related posts. It would be better to add that above so that it's clearly defined when the reader reaches the end of the sponsored content. Having that sit below related posts makes it much easier to miss. 

![Screen Shot on 2021-08-03 at 21-56-23](https://user-images.githubusercontent.com/22805865/128109652-69cf2d5c-48b4-46ca-9a00-57c181886611.png)

**Comment by dkoo** [comment]
Moving the sponsor info above Related Posts will also move it above other end-of-article elements that it normally appears after. For this reason I've asked @laurelfulford to weigh in on whether this is okay or if we should refrain from implementing. More details in the [pull request](https://github.com/Automattic/newspack-theme/pull/1792).
